### ISSUE TITLE
Fishing line is always rendered at full brightness

### ISSUE THREAD

**Issue by DmitriBogdanov** [Lightning-64/Tide#2]
# Version

**Minecraft:** 1.20.1
**Fabric:** 0.16.5
**Mod:** 1.3.1

# Issue

The fishing line is always rendered at full brightness without respecting the light level.

While it looks fine during the day, at night the bright texture really stands out from its surrounding, especially when using shaders.

# Screenshots

Without shaders, default fishing line:
![Screenshot](https://github.com/user-attachments/assets/7cc7cb6a-8414-47ad-88e6-59a7d84e0d9f)

With shaders, default fishing line:
![2024-09-25_22 03 57](https://github.com/user-attachments/assets/587910d3-7f9e-412f-b64a-7a4a39516fa0)

With shaders, golden fishing line:
![2024-09-25_22 19 50](https://github.com/user-attachments/assets/71e68c5c-2004-4886-8004-070ea1d2596e)

If rendering fishing line with proper brightness is technically difficult, it might be easier to just leave a "render vanilla fishing line" option in the config.

**Comment by Lightning-64** [comment]
Dynamic fishing line brightness is something I have experimented with because I've noticed this too, even without shaders. It is especially jarring sometimes underground.

In my tests I've found proper brightness to be very buggy, but this is a feature I would love to add, so I will definitely try again to make sure this is properly implemented. If I can't get it to work, I'll just add a config setting to render the default black line.

**Comment by Lightning-64** [comment]
A config setting to use the default black fishing line is added as of 1.3.2! I will try to add proper brightness in the future, but I'm closing this issue for now.

**Comment by Lightning-64** [comment]
It’s been a while, but proper fishing line brightness (no config setting needed) will be added in Tide 1.4 :)

**Comment by DmitriBogdanov** [comment]
Excellent news! Good to see such attention to mod's quality, there's few other mods to meaningfully change fishing on 1.20.1 Fabric, so this one is quite a highlight.
