### ISSUE TITLE
Custom Bobber Item Support

### ISSUE THREAD

**Issue by BrownBear85** [Lightning-64/Tide#26]
Hi again, I am still the developer of Stardew Fishing, and we would still like to be able to use Tide's bobber system to apply our custom bobber items. In my last issue, I hadn't gotten far into development to notice that custom bobber items are not actually supported currently. I saw the existence of a bobbers item tag and assumed it could be used to add custom bobbers, but that is not the case.

Currently any items besides Tide's bobber items are converted to a red bobber by default. Could you consider storing bobbers in nbt as an item id as supposed to an integer in order to support custom bobber items?

Thanks for your consideration!

**Comment by BrownBear85** [comment]
If you'd prefer, I could write the code for this and make a pull request.

**Comment by Lightning-64** [comment]
Sorry for seeing this so late! I've been a little busy lately.

I'll make sure that this is added in the next update. I haven't really given custom bobbers and hooks any though until now, which is why its not compatible currently. I'll come up with a better system for this when I can!

Also, the update might be a few weeks out still. There's some other things that I need to fix up before I can release it.

**Comment by BrownBear85** [comment]
No worries, and thank you! 

If you happen get the custom bobber part of the update done quicker than the rest, it'd be awesome if you could send me the incomplete build of the update with those features so I could get started on implementing Tide support. If not, or if you just don't wanna do that, no worries, I'll be patient! 😃

Thanks again

**Comment by Lightning-64** [comment]
Alright, I'll try to get that done within the week!

I've decided that I might just end up posting the build as soon as I'm done with the custom bobber stuff because I still have a bunch of bug fixes to work on and I don't want to leave you waiting. It should be no problem for me to split this update into two smaller ones.

**Comment by BrownBear85** [comment]
Alright, sounds good!

**Comment by Lightning-64** [comment]
Added as of 1.3.4!
