### ISSUE TITLE
Questions about performance

### ISSUE THREAD

**Issue by 79ak47** [Lightning-64/Tide#27]
Hello, author, Yesterday, when I was running spark to analyze server performance losses, found a fish-generated occupation, the only mod in the server for physical fish is tide. I don't know if this is tide's, if so, can the author addan option to disable physical fish generation in config, if it's not tide, please forgive me for interrupting. Thank you.
![Image_1729613751209](https://github.com/user-attachments/assets/5ac34522-e6bd-4015-8051-e6f99b0a3f73)

**Comment by Lightning-64** [comment]
Just by reading this, it looks like it's caused by an entity from Cobblemon! You can see this in the part where it says `com.cobblemon.mod.common.entity.pokemon.PokemonEntity.tick()`.

The physical fish entities from tide are basically identical to existing minecraft fish (cod, salmon, etc.) so there wouldn't be any reason why they would cause this (as far as I'm aware)

**Comment by Lightning-64** [comment]
The physical fish entities from tide are basically identical to existing minecraft fish (cod, salmon, etc.) so there wouldn't be any obvious reason why they would cause this, as far as I'm aware.

This could be due to the fact that there are simply more fish in the game than usual, therefore the game has to spawn and tick more fish in the world. It could also be something else that I'm missing though, I'm not entirely sure.

**Comment by 79ak47** [comment]
OK, thank you for your reply.
